### ISSUE TITLE
Assertion failed error

### ISSUE THREAD

**Issue by kriszyp** [edvakf/node-tokyocabinet#2]
When I run the sync example code, I get the following error:

Assertion failed: (false), function ArgsData, file ../src/tokyocabinet.cc, line 290.

Any suggestion how to fix this?

**Comment by edvakf** [comment]
I made some fix that's not been pushed yet. I've left it so long that I can't remember what I did... I'll push it in a week or so if there are no problems.

**Comment by kriszyp** [comment]
Ah, great to hear, I am excited to use this library, looks awesome (and it looks like sync mode could be vastly faster than async, eio_custom is very expensive).

**Comment by hassy** [comment]
Getting the same error, on two different systems. Any word on when the fix may be available?

**Comment by ghost** [comment]
I have a patch for the line 290 assertion in ArgsData. Actually is a bigger problem in the virtual inheritance hierarchy. http://github.com/vasco-da-gama/node-tokyocabinet/commit/eedf79263d503280aa143cb98082d01826c2db69

**Comment by edvakf** [comment]
Done. 

As Kris said, sync was 7 times faster. It's a shame to have to use sync IO on node.js, but I guess there is no choice with this performance difference.
